common: &common
  encoding: unicode
  adapter: postgresql
  host: localhost
  pool: 5

development:
  <<: *common
  database: insta_db_dev

test:
  <<: *common
  database: insta_db_tst

production:
  <<: *common
  database: insta_db_pro
  pool: 25
